[package]
name = "kernel-trace"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
kernel-trace-common = { path = "../kernel-trace-common", features = ["user"] }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
    "time",
] }

[build-dependencies]
anyhow = { workspace = true }
