# NDK 路径：darwin-x86_64 上以 /Users/freeman/Library/Android/sdk/ndk 为准
[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
linker = "/Users/freeman/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang"
ar = "/Users/freeman/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
rustflags = [
  "-l", "clang_rt.builtins-aarch64",
  "-L", "/Users/freeman/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/18/lib/baremetal",
]

[env]
CC_aarch64-linux-android = "/Users/freeman/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang"
BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=/Users/freeman/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/sysroot"
